stages:
  - build
  - test
  - build-2
  - package
  - publish
  - release

variables:
  BROKER_PROJECT_ID: 46515078
  BROKER_BRANCH: main

default:
  before_script:
    - VERSION=${CI_COMMIT_TAG}
    - "[ -z \"$VERSION\" ] && VERSION=0.0.${CI_PIPELINE_IID}"
    - export VERSION

build js client:
  stage: build
  image: node:16-slim
  script:
    - apt-get update -qq
    - apt-get install -qq curl unzip
    - scripts/get_protobuf.sh
    - cd js
    - sed -i "s/0.0.1-dev-version/${VERSION}/g" package.json src/constants.ts webpack.config.cjs
    - npm install
    - ./generate.sh
    - npm run build
    - npm pack
  artifacts:
    paths:
      - js/src/constants.ts
      - js/src/generated
      - js/package.json
      - js/lib
      - js/dist
      - js/inhumate*.tgz
    expire_in: 1 week
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - protobuf
      - js/node_modules

test js client:
  stage: test
  image: node:16-slim
  needs:
    - build js client
  script:
    - apt-get update -qq && apt-get install -qq curl unzip
    - "curl --location --output artifacts.zip --header \"JOB-TOKEN: ${CI_JOB_TOKEN}\" \"https://gitlab.com/api/v4/projects/${BROKER_PROJECT_ID}/jobs/artifacts/${BROKER_BRANCH}/download?job=build%20broker\" && unzip artifacts.zip && rm -f artifacts.zip"
    - node broker/dist/broker.js &
    - sleep 10
    - cd js
    - npm install
    - npm run test-ci
  artifacts:
    reports:
      junit:
        - js/junit.xml
  cache:
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - js/node_modules
